// <auto-generated />
using System;
using CarPupsTelegramBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarPupsTelegramBot.Migrations
{
    [DbContext(typeof(CarPupsTelegramBotContext))]
    partial class CarPupsTelegramBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("CarPupsTelegramBot.Models.FuellyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FuellyId");

                    b.HasKey("Id");

                    b.ToTable("Fuelly");
                });
#pragma warning restore 612, 618
        }
    }
}
