// <auto-generated />
using System;
using CarPupsTelegramBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarPupsTelegramBot.Migrations
{
    [DbContext(typeof(CarPupsTelegramBotContext))]
    partial class CarPupsTelegramBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("CarPupsTelegramBot.Models.GarageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DriveType");

                    b.Property<string>("EngineCode");

                    b.Property<int?>("EngineFuel");

                    b.Property<string>("EngineSize");

                    b.Property<int?>("EngineType");

                    b.Property<int>("FuellyId");

                    b.Property<string>("Generation");

                    b.Property<string>("MainImage");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<string>("Plate");

                    b.Property<int?>("Transmission");

                    b.Property<long?>("UserTelegramId");

                    b.HasKey("Id");

                    b.HasIndex("UserTelegramId");

                    b.ToTable("Garage");
                });

            modelBuilder.Entity("CarPupsTelegramBot.Models.UserModel", b =>
                {
                    b.Property<long>("TelegramId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TelegramName");

                    b.Property<string>("TelegramUsername");

                    b.HasKey("TelegramId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarPupsTelegramBot.Models.GarageModel", b =>
                {
                    b.HasOne("CarPupsTelegramBot.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserTelegramId");
                });
#pragma warning restore 612, 618
        }
    }
}
